apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "easm-frontend.serviceAccountName" . }}
  labels:
    {{- include "easm-frontend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
